name: Terraform Plan and Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set KUBERNETES variables
        run: |
          export KUBE_HOST=$(aws eks --region ${{ secrets.AWS_REGION }} describe-cluster --name fiap-challenge-cluster --query "cluster.endpoint" --output text)
          export KUBE_CA_CERT=$(aws eks --region ${{ secrets.AWS_REGION }} describe-cluster --name fiap-challenge-cluster --query "cluster.certificateAuthority.data" --output text)
          export KUBE_TOKEN=$(aws eks --region ${{ secrets.AWS_REGION }} get-token --cluster-name fiap-challenge-cluster --query "status.token" --output text)

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
